name: cloudrun-deploy
on:
  push:
    branches: [master, Dev]
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    env:
      DEV_GCM_PROJECT: ${{ secrets.GCM_PROJECT }}
      MASTER_GCM_PROJECT: "master"
      DEV_GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      MASTER_GCP_CREDENTIALS: "master"
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 100

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0.2.0
      if: github.ref == 'refs/heads/Dev'
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0.2.0
      if: github.ref == 'refs/heads/master'
      with:
        project_id: ${{ secrets.MASTER_GCP_PROJECT }}
        service_account_key: ${{ secrets.MASTER_GCP_CREDENTIALS }}
        export_default_credentials: true

    - name: Check HelloWorld changes...
      uses: marceloprado/has-changed-path@v1
      id: helloworld
      with:
        paths: hello_world/**

      # Deploy the Docker image to the GKE cluster
    - name: Deploy
      if: steps.helloworld.outputs.changed == 'true'
      run: |
        gcloud run deploy helloworld --source=hello_world \
        --platform managed --allow-unauthenticated --region=us-central1 \
        --set-env-vars=[LOCATION_GQL_URL="http://us-central1-leasera-200719.cloudfunctions.net/location"]