name: cloudrun-deploy
on:
  push:
    branches:
      - master
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 100

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |
        gcloud run deploy helloworld --source=hello_world --service-account ${{ secrets.GCP_EMAIL }} \
        --platform managed \
        --allow-unauthenticated \
        --region=us-central1
        --memory 512M