name: cloudrun-deploy
on:
  push:
    branches:
      - master
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 100

    - name: Determine GCP Project
      if: github.ref == 'refs/heads/Dev'
      run: echo "PROJECT_ID=$(echo $GCP_EMAIL)" >> $GITHUB_ENV

    - name: Determine GCP Project
      if: github.ref == 'refs/heads/master'
      run: echo "PROJECT_ID=$( echo ${{ GCP_PROJECT }} )" >> $GITHUB_ENV


    - name: Use conditional value
      run : echo "${{ env.PROJECT_ID }}"
#      run: echo "${{ github.ref }}"

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${PROJECT_ID}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true

    - name: Check HelloWorld changes...
      uses: marceloprado/has-changed-path@v1
      id: helloworld
      with:
        paths: hello_world/**

      # Deploy the Docker image to the GKE cluster
    - name: Deploy
      if: steps.helloworld.outputs.changed == 'true'
      run: |
        gcloud run deploy helloworld --source=hello_world --service-account ${{ secrets.GCP_EMAIL }} \
        --platform managed --allow-unauthenticated --region=us-central1 \
        --set-env-vars=[LOCATION_GQL_URL="http://us-central1-leasera-200719.cloudfunctions.net/location", \
        THIRD_PARTY_AUTH_URL="https://us-central1-leasera-200719.cloudfunctions.net/third_party_auth"]